### PR TITLE
Fix left-over bytes vs string issue

### PR DESCRIPTION
**Pull request by IcePhoenX**
Fix of issue [#47](https://github.com/anishathalye/git-remote-dropbox/issues/47)

### CODE REVIEW

**Comment by anishathalye** [comment]
Was this directly causing the issue? / Do you know how to reproduce the failure in #47, such that the code fails without this patch?

**Comment by IcePhoenX** [comment]
I'm not sure because, this is my first time using this and it never worked without it for me.
Win7, Python 3.5.1, git 2.11.1.windows.1
I'm in the same situation as the OP in #47. Create a new repo with git init, push it to dropbox, then try to clone it, and got the same exception. After debugging it, I think this was the issue.
I think _git_encode_object_ and _git_decode_object_ should be symmetrical, therefore kind needs to be decoded.

**Comment by anishathalye** [comment]
Hmm, so doing `.decode('utf8')` converts from bytes to string. So this can't be the cause of the issue in #47, "a bytes-like object is required, not 'str'".

I tried the code both with and without this patch on Python 3 / Mac OS, and it works fine both ways. I think `subprocess.Popen` can take an array of bytes or strings...

**Comment by IcePhoenX** [comment]
Actually that exception is a little bit misleading.
Following the stack trace, that exception is raised in
```
File "...\Python35\lib\subprocess.py", line 754, in list2cmdline
	needquote = (" " in arg) or ("\t" in arg) or not arg
```
The actual content of `arg` when the exception arise in my test case is `b'commit'` (if `kind` is not decoded, it remains a bytestring)
Therefore `" " in b'commit'` is actually complaining about that `" "` is not a bytes-like object

**Judging from [this](https://github.com/ionelmc/python-ghp-import/pull/1), this might be a windows specific thing.**

**Comment by anishathalye** [comment]
Ah, thanks for getting to the bottom of this! Your fix is included in v0.2.3.

**Pull request merged**
